
<?php
chdir(__DIR__);

$file_to_require=realpath('./../../fpdf.php');

require($file_to_require);
 unset($file_to_require);
chdir(__DIR__);


   session_start();
  $ticket=$_SESSION['ticket'];
   $date=$_SESSION['date'];
   $name=$_SESSION['namePDF'];
   $address=$_SESSION['address'];
   $contact=$_SESSION['contact'];
   $category=$_SESSION['category'];
   $classification=$_SESSION['classification'];
   $item=$_SESSION['item'];
   $principal=$_SESSION['principal'];
   $contract=$_SESSION['contract'];
   $months=$_SESSION['months'];
   $chargevalue=$_SESSION['chargevalue'];

 $fpdf=new FPDF();
 $fpdf->AddPage();
 $fpdf->SetFont('courier','B',15);
 $fpdf->SetLeftMargin(20);
 $fpdf->SetRightMargin(20);
 $fpdf->Ln(5);
 $fpdf->Rect(10,10,190,278,'D');
 $fpdf->Cell(0,10,'Original', 0, 0, 'L');
 $fpdf->Cell(-30,10,'Pawn Ticket Number: ' , 0, 0, 'R');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(0,10, $ticket , 0, 0, 'R');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,30,'Date Loan Granted: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,30, $date , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(0,50,'Pawner Information', 0, 0, 'C');
 $fpdf->Ln(10);
 $fpdf->Cell(0,50,'----------|||----------', 0, 0, 'C');
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Pawner Name: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,50, $name , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Address: ' , 0, 0, 'L');
 $fpdf->Ln(10);
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,50, $address , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Contact Number: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,50, $contact , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(20);
 $fpdf->Cell(0,50,'Item Information', 0, 0, 'C');
 $fpdf->Ln(5);
 $fpdf->Cell(0,50,'----------|||----------', 0, 0, 'C');
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Category: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,50, $category , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Classification: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(60,50, $classification , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(20);
 $fpdf->Cell(0,50,'Loan Information', 0, 0, 'C');
 $fpdf->Ln(5);
 $fpdf->Cell(0,50,'----------|||----------', 0, 0, 'C');
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Contract Duration: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(0,50, $contract , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Due Date: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(0,50, $months , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Principal Loan: P' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(0,50, $principal , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Monthly Interest: ' , 0, 0, 'L');
 $fpdf->SetFont('courier','U',15);
 $fpdf->Cell(0,50, $chargevalue , 0, 0, 'L');
 $fpdf->SetFont('courier','B',15);
 $fpdf->Ln(20);
 $fpdf->Cell(60,50,'_________________ ', 0, 0, 'L');
 $fpdf->Cell(0,50,'_________________ ', 0, 0, 'R');
 $fpdf->Ln(10);
 $fpdf->Cell(60,50,'Pawner Signature', 0, 0, 'L');
 $fpdf->Cell(0,50,'Employee Signature', 0, 0, 'R');
 $fpdf->output();
?>
